### PR TITLE
Set up CircleCI integration

### PR DESCRIPTION
**Pull request by TheKevJames**

### CODE REVIEW

**Comment by TheKevJames** [comment]
@goanpeca once this is merged, lets update #106 to ensure CircleCI works with that patch

**Comment by goanpeca** [comment]
why is travis failing?

**Comment by TheKevJames** [comment]
Huh, looks like circle completes so much faster than travis that coveralls is rejecting the payload from travis as already-received. (I think) we should have only one of them send coverage data to coveralls. Any preference as to which?

**Comment by goanpeca** [comment]
Travis should be fine I guess, as we dont have to configure the repo token.

Also moving forward I would advice making PRs against a fork of the repo and not against a branch in the repo.

**Comment by TheKevJames** [comment]
Hmm looks like I'm a liar, coveralls just happened to timeout during these tests. Re-running them to be sure.

I can fork and work there, but may I ask why? Seems strictly more convenient to work from this repo, given we have write-access.

**Comment by goanpeca** [comment]
1. Its a better workflow to use forks independent if you are the owner or not of the repo and helps avoid accidental pushes to wrong branches in the official repo. If there is an accidental push to your fork, it is much better than if it happens to the original repo
2. We can avoid having 2 builds for travis (pr and push)
3. Its just how normal contributions work on OS projects so helps keep the same mental model for all projects (at lease in my case)

**Pull request merged**
