### PR TITLE
docs(usage): Simplify tox.ini example

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by TheKevJames** [comment]
Hey there! Thanks for the contribution.

I think making explicit which environment variables are important in each environment is important, so everyone knows exactly which values are important. If you'd like to update the docs to mention the `*` syntax as an additional option, we'd be happy to accept that.

**Comment by asottile** [comment]
did you mean to close this? I _could_ do the adjustments you're asking for without needing to make a new branch and new PR (which is both inconvenient and loses context)

**Comment by TheKevJames** [comment]
Ah, my bad, meant to click "comment" but clicked "close and comment" instead. Sorry about that!

**Comment by asottile** [comment]
@TheKevJames since I think the wildcard syntax is way more convenient and future-proof than enumerating each variable in the config, would you be ok with me listing the current list of necessary environment variables above the configuration and leave what I have otherwise?

I have a feeling that people are going to copy paste the configuration once and don't really care too much about the specific environment variables -- I do agree that documenting them is a positive though!

**Comment by TheKevJames** [comment]
Yup, that sounds good to me.

As an aside, could you please make sure to include [this env var change](https://github.com/coveralls-clients/coveralls-python/pull/171/files#diff-03b1a1aff2c2a1e98be2ff882cf556b6R43) which was just merged?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d8f6ca19100a4b6e0742d45f0a82e5d5eef8a4c7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/coveralls-clients/coveralls-python

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 22779eb3428040681098d7f786408a84e2fefe66
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/coveralls-clients/coveralls-python

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7f28f30b0c0ced00fcda6b0404e181eeba3548b3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/coveralls-clients/coveralls-python

---
This message was auto-generated by https://gitcop.com

**Comment by TheKevJames** [comment]
Looks good! Thanks for dealing with the nitpicks :)

**Pull request merged**
