### PR TITLE
Fix unhashable exception

### PR DESCRIPTION
**Pull request by rodrigc**
Fixes https://github.com/coveralls-clients/coveralls-python/issues/229

### CODE REVIEW

**Comment by TheKevJames** [comment]
@rodrigc appreciate the quick fix, thanks!

**Comment by rodrigc** [comment]
@TheKevJames Thanks for merging the fix.  I can confirm that it works.  In the Twisted project, I am occasionally seeing errors, such as the one at this link: https://travis-ci.com/github/twisted/twisted/jobs/361796000

that look like:

```
Submitting coverage to coveralls.io...
Could not submit coverage: 504 Server Error: Gateway Time-out for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/home/travis/build/twisted/twisted/build/coveralls-push/lib/python3.6/site-packages/coveralls/api.py", line 205, in wear
    response.raise_for_status()
  File "/home/travis/build/twisted/twisted/build/coveralls-push/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://coveralls.io/api/v1/jobs
```

Is there a problem on the coveralls server?

**Comment by rodrigc** [comment]
I also saw this error at https://travis-ci.com/github/twisted/twisted/jobs/361796000


```

coveralls-push run-test: commands[1] | coveralls
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/home/travis/build/twisted/twisted/build/coveralls-push/lib/python3.6/site-packages/coveralls/api.py", line 205, in wear
    response.raise_for_status()
  File "/home/travis/build/twisted/twisted/build/coveralls-push/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/twisted/twisted/build/coveralls-push/lib/python3.6/site-packages/coveralls/cli.py", line 85, in main
    result = coverallz.wear()
  File "/home/travis/build/twisted/twisted/build/coveralls-push/lib/python3.6/site-packages/coveralls/api.py", line 208, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
ERROR: InvocationError for command /home/travis/build/twisted/twisted/build/coveralls-push/bin/coveralls (exited with code 1)
```

**Comment by TheKevJames** [comment]
Unfortunately, it seems the Coveralls API just isn't all that reliable -- we've gotten a bunch of reports like this (and other coveralls libraries have seen the same sort of thing) and they mostly just amount to intermittent API issues. We're not associated with Coveralls at all, so there's nothing I can do there. The 422 error might be something on our side -- if you can reproduce it within some specific set of inputs, it might be something we can avoid! Feel free to open up an issue if so, I'd be happy to take a look.

**Comment by rodrigc** [comment]
Thanks for the response.  Yes this was an intermittent problem and I have not hit it lately.
The workaround for me was to push a new commit to my branch so that it would have a new Git SHA, and Coveralls did not error out after that.

**Pull request merged**
