### PR TITLE
Support parallel builds in the client

### PR DESCRIPTION
**Pull request by indradhanush**
[Review on Reviewable](https://reviewable.io/reviews/coagulant/coveralls-python/106)

### CODE REVIEW

**Comment by coagulant** [comment]
Please, add test and documentation.

**Comment by TheKevJames** [comment]
Hey there! This repo just underwent a change in maintainers -- myself and @goanpeca will be taking over this project. Give us some time to get up-to-speed and we'll make sure to take a look at this PR soon.

**Comment by TheKevJames** [comment]
Hey there! Sorry for getting back to you so late.

This repo was moved to a new home on Github, so we lost all travis results on active PRs. Would you mind either resubmitting this PR or pushing an update so we can kick off a new run? Thanks!

@goanpeca: what do you think about setting ourselves up with CircleCI and Appveyor CI (in addition to Travis), to help us test PRs like this?

**Comment by goanpeca** [comment]
@TheKevJames sure, please open a tickt and assign to me ;-)

**Comment by indradhanush** [comment]
@TheKevJames Could you point me to the new home where I should send this PR? I was unable to find it. :(

**Comment by TheKevJames** [comment]
Sorry about that, I misspoke a bit: the "new home" is right here (https://github.com/coveralls-clients/coveralls-python). The only issue is the checks attached to this PR are still pointing to the old home. (coagulent/coveralls-python).

**Comment by indradhanush** [comment]
@TheKevJames I just rebased master onto mine and pushed.

**Comment by TheKevJames** [comment]
Looks good! Once we test this with circle (issue #150), this looks good to go.

**Comment by TheKevJames** [comment]
Hey, sorry to ask this again, could you rebase off the latest master? We just set up circle integration.

**Pull request merged**
