### PR TITLE
Add Python 3.6 to testing

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by goanpeca** [comment]
@cclauss thanks for your contribution.

---

@TheKevJames I don't think we should be running tests on 3.3 or 3.4. We should probably limit to 2.7, 3.5 and 3.6 (the two latests releases)

Thoughts?

**Comment by cclauss** [comment]
Thanks @goanpeca but I can NOT make it work.  ;-(  Python 3.6 seems to work fine with Cov41 but NOT with Cov4 or Cov3.  My tox skills are not good enough to test Python 3.6 against only Cov41 while having all other Python test against Cov3, Cov4, and Cov41.

**Comment by jvarho** [comment]
@cclauss Try:

envlist = py{27,33,34,35,py,py3,py-54,py33-52-alpha1}-cov{3,4,41}-{default,pyyaml},py36-cov41-{default,pyyaml}

Or maybe py3 needs to be moved to the second pattern as well in case it points to 3.6 (now or at some point in the future).

**Comment by TheKevJames** [comment]
@cclauss Hmm, I see from https://travis-ci.org/coveralls-clients/coveralls-python/builds/209018580 that `py36-cov3` and `py36-cov4` are failing assertions in our tests rather than `py36` being incompatible with those `cov` versions. I don't have to time to investigate deeper right now, but maybe we should see if we can fix those comparisons rather than avoiding testing of those environments?

@goanpeca For most libraries, I would generally agree. In our case, though, I think we want to try to keep our compatibility equivalent to [coverage.py's](https://coverage.readthedocs.io/en/coverage-4.3.4/).

They say they support:
> - Python versions 2.6, 2.7, 3.3, 3.4, 3.5, and 3.6.
> - PyPy2 5.6 and PyPy3 5.5.
> - Jython 2.7.1, though only for running code, not reporting.

I think we should support the same (we can ignore Jython, since they don't cover reporting anyway).

**Comment by jvarho** [comment]
The issue seems to be that with coverage.py <4.1 branch reporting does not work under Python 3.6.

(This is with coverage==4.0 installed.)

$ python3.5 -m coverage run --branch example/runtests.py  && python3.5 -m coverage report
world
condition not tested both ways
condition tested both ways
condition not tested both ways
Name                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------
example/project.py       10      1      4      1    86%
example/runtests.py       5      0      2      1    86%
-------------------------------------------------------
TOTAL                    15      1      6      2    86%
$ python3.6 -m coverage run --branch example/runtests.py  && python3.6 -m coverage report
world
condition not tested both ways
condition tested both ways
condition not tested both ways
Name                  Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------
example/project.py       10      1      0      0    90%
example/runtests.py       5      0      0      0   100%
-------------------------------------------------------
TOTAL                    15      1      0      0    93%

**Comment by TheKevJames** [comment]
Ah, got it. In that case, I guess we'll have to test py36 only with cov41+. Can we do that on travis, as well as in tox?

As for dropping support of older versions, I'm a bit iffy on that. I don't see a good reason why we should -- is it not strictly better to ensure old versions work than leaving anyone who hasn't updated or for some reason can't update in trouble?

**Comment by TheKevJames** [comment]
Closed in favor of superset PR #149. Thanks for kicking this off @cclauss !

**Pull request closed without merging**
