### PR TITLE
Added Travis Pull Request support

### PR DESCRIPTION
**Pull request by nickmerwin**
Will set `service_pull_request` if `TRAVIS_PULL_REQUEST` is set.

---

This change is [Reviewable](https://reviewable.io/reviews/coagulant/coveralls-python/113)

### CODE REVIEW

**Comment by coagulant** [comment]
Please add test for your PR, if you have time.

**Comment by TheKevJames** [comment]
Hey there! This repo just underwent a change in maintainers -- myself and @goanpeca will be taking over this project. Give us some time to get up-to-speed and we'll make sure to take a look at this PR soon.

**Comment by TheKevJames** [comment]
Hey there! Sorry it took so long to get back to you.

This project got moved to a new github org and it looks like that removed all the test results. Would you mind re-submitting this pull request, or pushing something to this branch, so we could have github run tests against it?

Thanks!

**Comment by TheKevJames** [comment]
Moved to #162

**Pull request closed without merging**
